[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
# ignore warnings about unused parameters
# and code size and init code size: the code size
# issue is not relevant because
# this repository does not make any deployments.
ignored_error_codes = [5667, 5574, 3860]
ignored_warnings_from = ["script"]
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer = true
optimizer_runs = 200
solc = "0.8.28"

# turn off the annoying linter
[lint]
exclude_lints = [
    "unused-import",
    "unaliased-plain-import",
    "mixed-case-variable",
    "mixed-case-function",
    "unsafe-typecast",
    "unsafe-cheatcode"
]
